version: "3.9"

services:
  laravel-new:
    image: laravel:latest
    build:
      context: ./project-new
      dockerfile: ./Dockerfile
    container_name: laravel-new
    expose:
      - 9000
    volumes:
      - ./project-new/project-new/:/var/www/project-new.net
    networks:
      - trade
    depends_on:
      - mysql-project

  nginx-project:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.config/nginx/server:/etc/nginx/conf.d
      - ./.config/nginx/logs/:/var/log/nginx
      - ./frontend/:/var/www/html
      - ./project-new/project-new/:/var/www/project-new.net
    depends_on:
      - laravel-new
    networks:
      - trade

  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-admin.project.net
    restart: always
    environment:
      - PMA_HOST=${PMA_HOST}
    ports:
      - "8080:80"
    depends_on:
      - mysql-project
    networks:
      - trade

  mysql-project:
    restart: always
    container_name: mysql-project
    image: mysql:8.1
    ports:
      - 3311:3306
    volumes:
      - ./.config/server/data/mysql:/var/lib/mysql
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - trade

networks:
  trade:
    driver: bridge
    name: trade